### PR TITLE
working: series flow redesign

### PR DESCRIPTION
**Pull request by giveadan**

### CODE REVIEW

**Comment by giveadan** [comment]
Design to dos:
- [x] - mobile friendly all layouts (confirm cards collapse probably)
- [x] - add list of category tags to series index
- [x] - overlay image for pro videos
- [ ] - full width personalized msg component from @jeffreybiles encouraging user to support
- [ ] - run through and small touchups

**Comment by jeffreybiles** [comment]
Great discussion today in person!  Looking forward to the next version.

**Comment by giveadan** [comment]
@jeffreybiles you can run through this and let me know what touchups need to be made

**Comment by jeffreybiles** [comment]
Will do!  I'll run through it tomorrow and leave comments :)

**Comment by jeffreybiles** [comment]
Here's my thoughts so far:
- Explore page looks good.  We'll need a separate tags page, since the explore page no longer has links to them.
- video show page
  - The call to action for non-pro members is fantastic
  - Where did the previous/next buttons go?
  - On the series box, how are we marking the the currently selected one?
  - Make “series” header a clickable link
  - Weren’t we going to cut off the number and dash on the video title?
  - Where are the tags?
  - I’m not sure about the highlighting on the page header.
- Don’t cut off episode titles in the series show page
- The styling that works great for the series show page doesn't work great for the tag show page.

**Comment by giveadan** [comment]
Just pushed up the changes with mostly everything you mentioned. The only
thing is having an active tag to current video page. That will take a tad
bit more time. Everything else seems to be good. Take a look and let me
know!

**Comment by jeffreybiles** [comment]
Much improved.  However, these changes introduced some more visual bugs.
- Next and previous links aren't lined up vertically- next is lower than previous
- Tags and speed buttons aren't lined up vertically- speed is conspicuously higher than the tags
- 
  screen shot 2016-05-18 at 7 07 19 pm
- Highlighting of the series name has very sharp edges.  Should we round them or keep as-is?
- Great job on on the new footer.

In the future if any changes I suggest produce new visual bugs, please either fix them as you're working or report back to me about anything that's too difficult.

**Comment by jeffreybiles** [comment]
Good job on the specific things I mentioned.  There's some other stuff I've found, but I'll take it from here.

**Pull request merged**
