### PR TITLE
working: Algoliasearch instantsearch results

### PR DESCRIPTION
**Pull request by mglobel**
## To do
- [x] server side index configuration (for sorting, etc)
- [x] display free/premium tag on results page
- [x] clean up styles with latest merge

### CODE REVIEW

**Comment by mglobel** [comment]
@jeffreybiles got the indices configured. there's a cpl other settings i want to review and possibly add to the post model. looks like there's some conflicts with the latest merge too. i'll clean up this afternoon and finalize. 

but you can check out the latest commit for the indices configuration!

**Comment by jeffreybiles** [comment]
Awesome, looks like the indices API was pretty good.

Let me know when the cleanup is done and you're ready to merge.  By the way, you can use the new styles now if you rebase!

**Comment by mglobel** [comment]
hey @jeffreybiles merged in some helper methods, mostly applying humanized time and date formats to the search results page. could probably be improved styling..but let me know what you think for an mvp.

Things should be good for server side though. I did some research on path's we can take when it comes time for series and subjects..and main gist is that we're on a fine path to accomadate for that down the line.

**Comment by jeffreybiles** [comment]
Looks pretty good!  Rebase to get the new `display_title` and I'll be ready to merge.

**Comment by mglobel** [comment]
latest merged. should be good 🎉

**Comment by jeffreybiles** [comment]
Woohoo!  Pushing to heroku.

**Comment by jeffreybiles** [comment]
I pushed to heroku, but I had to roll back because we don't have production indices.  Please add those.

**Comment by mglobel** [comment]
Hmm, two things I think.

1)  Needed to add ALGOLIASEARCH_API_KEY_SEARCH to env. Heroku automatically
added the other two, but not that one.

2) I think need to hop on `heroku run rails console -a emberscreencasts`
and run `Post.index!` once it's pushed up, which should then auto create
the production indices. Forgot about that as a deploy step

On Wed, May 25, 2016 at 11:52 AM, Jeffrey Biles notifications@github.com
wrote:

> I pushed to heroku, but I had to roll back because we don't have
> production indices. Please add those.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jeffreybiles/simpler-ember-sparks-website/pull/20#issuecomment-221634394

## 

Michael Lobel | MyTennisLessons
_Client Success Coordinator_
Toll-free: (866) 454-2747

**Comment by jeffreybiles** [comment]
Ah, I figured out the first part but nor the second.  Hopefully I'll get
this up this afternoon!  P.S. does it reindex automatically?

**Comment by mglobel** [comment]
It does! Uses active record callbacks for individual records. And then you
can call reindex! if you add new attrs, after deploying to update things.
I'll add a comment as a reminder in one of my next commits..

**Comment by jeffreybiles** [comment]
FYI, Post.index! failed (not enough arguments), but Post.index worked.

**Comment by mglobel** [comment]
Hmm, interesting, and good to know. But now it lives!! 👏

**Pull request merged**
