### PR TITLE
Remove publish date and transcript from searchable index

### PR DESCRIPTION
**Pull request by mglobel**
Post release
- [ ] run Post.reindex! on console

### CODE REVIEW

**Comment by jeffreybiles** [comment]
I definitely agree on removing publish date, but it may be useful to be able to find stuff that's in the transcript.  Is there a way to make the results from the transcript have less value than the results from fields like display_title and description? (1 mention in the display_title is worth, say, 3 mentions in the description or 10 mentions in the transcript)

**Comment by jeffreybiles** [comment]
Is there a way to get smart fuzzy search?  If you search for "defend", it
would match "defense" but not "defined" or "defenestrate"

**Comment by mglobel** [comment]
Hola! Took the memorial day weekend a bit lax, getting back into things today.

But to answer le questions:
1) Can definitely rank the priority of the results. Don't think you can get as granular as those settings, but you can put them in a certain order, and they do the algorithm to rank them accordingly.

2) You can somewhat related things, but I don't think you can be that specific. Here's what you can do that I know:
- add a synonym list (defend, defense, defender)
- add 'optional words' that are ignored during search. already included are things like 'the' and 'a'
- change around typo tolerance settings

**Comment by mglobel** [comment]
@jeffreybiles transcript added back to indices

**Comment by jeffreybiles** [comment]
Hope your memorial day weekend was good!

I think we'll want to decrease our typo tolerance then (maybe to 0)- people
will be used to typing in exact searches, but dealing with bad fuzzy search
is confusing.

And yes, let's definitely rank them in the algorithm.

**Pull request merged**
