### PR TITLE
Homepage and Pricing Redesign

### PR DESCRIPTION
**Pull request by mglobel**
Howdy Sir @jeffreybiles, hope San Francisco is treating you well! @giveadan and I wrapped up implementing the home page, pricing page, and custom stripe form today, included in this PR. Take a look when you get a chance this week and feel free to post any comments or questions on here. If there's anything you'd like to discuss more in-depth with this phase, we can hop on a hangout or discuss in person when you return.

Once everything looks good, feel free to merge when you're ready and I can send over a W-9 and/or invoice!

Peace and code,
Mike and Dan

Some notes:
- pay.html.erb includes both the form and the js for validating and getting the stripe token. If this were a project where a bunch of people were contributing, I'd say break it up for organization. Since it's mostly just you on here, I opted for keeping it in one file for simplicity sake. Which ever you prefer though.
- pay.html.erb currently has the password field commented out, as that'll require some controller changes and I didn't want mess with your current paid signup flow too much. Should be pretty simple to flip on though with a couple controller edits.
- I was getting issues with an 'Invalid Authenticity Token' on the accounts_controller#subscribe action, similar to this issue: [StackOverflow- Invalid authenticity token](http://stackoverflow.com/questions/20875591/actioncontrollerinvalidauthenticitytoken-in-registrationscontrollercreate).  I added a `skip_before_action :verify_authenticity_token` on the accounts controller, not sure if there's further ramifications for that though..

Implementation to-do:
- [ ] swap out default stripe plan in accounts_controller.rb

To view work (I'm pretty sure):
(skip these if you already have a remote for the MikeAndDan fork)
-`git remote add mikeanddan https://github.com/MikeAndDan/simpler-ember-sparks-website.git`
-`git fetch mikeanddan`

-`git checkout homepage-pricing-and-redesign`

**I actually tried pushing this up to a demo heroku app, but was running into some issues on the pre-compile. If you've got a staging app, could definitely hop over to that and push it up.

### CODE REVIEW

**Comment by jeffreybiles** [comment]
Awesome, thanks for the update!  

I've been super busy in SF (I got invited to the FluentConf speaker dinner... you don't say no to that!) but I'm going to dig into this Saturday morning so I'll be ready to talk about it when we meet up.

**Comment by mglobel** [comment]
Sounds good. Live it up!

**Comment by mglobel** [comment]
@jeffreybiles, ran through our discussion on saturday with @giveadan, and pushed up some solutions:

1) Sales page btn is now a ghost btn (that's actually what was in the mockup)
screenshot 2016-03-14 11 29 51

2) Add background color to ghost btn on hover (pretend like cursor is over the button..manually triggered the hover state for screenshot purposes)
screenshot 2016-03-14 11 31 44

**Comment by jeffreybiles** [comment]
This looks fantastic!  I'm with fam right now, will take care of merging + payment either tomorrow (hopefully) or Friday (at the latest)

**Pull request merged**
